name: L10n
on:
  pull_request_target:
    branches:
      - main
      - master
      - stable*

jobs:
  auto-approve-merge:
    if: github.actor == 'Transifex-localization-platform[bot]' || github.actor == 'transifex-integration[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: pascalgn/automerge-action@v0.15.3
        env:
          MERGE_DELETE_BRANCH: true
          MERGE_LABELS: ''
          MERGE_RETRIES: 6
          MERGE_RETRY_SLEEP: 30000
          GITHUB_TOKEN: ${{ secrets.COMMAND_BOT_PAT }}
