name: Transifex
on: pull_request

jobs:
  auto-approve-merge:
    if: github.event.pull_request.user.login == 'transifex-integration[bot]'
    runs-on: ubuntu-latest

    steps:
      # Github actions bot approve
      - uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.COMMAND_BOT_PAT }}

      # Nextcloud bot merge
      - uses: pascalgn/automerge-action@v0.16.3
        env:
          MERGE_DELETE_BRANCH: true
          MERGE_LABELS: ''
          MERGE_RETRIES: 6
          MERGE_RETRY_SLEEP: 60000
          GITHUB_TOKEN: ${{ secrets.COMMAND_BOT_PAT }}
